### PR TITLE
let `.babelrc` not be added to package

### PR DESCRIPTION
**Pull request by HsuTing**

### CODE REVIEW

**Comment by ryan-roemer** [comment]
You don't want to add `.babelrc` to `.npmignore` in the repository itself, because this will break `git`-based installations. This is because in a git-based installation, `npm pack` equivalent is run, which will remove `.npmignore`-ed files, and here the `.babelrc`, which is necessary for the `git` version to actually build `lib/` and `dist/` from scratch.

We likely want to close this PR in favor of https://github.com/FormidableLabs/radium/issues/731 which will optimally, _not_ have `.babelrc` in the `npm` registry version of Radium, but maintain it in git source.

**Comment by HsuTing** [comment]
That`s great. I`m glad to hear that.

**Comment by alexlande** [comment]
Closing this now that https://github.com/FormidableLabs/radium/pull/914 has landed.

**Comment by ryan-roemer** [comment]
@alexlande -- We actually still do have `.babelrc` in the npm published version: https://github.com/FormidableLabs/radium/blob/master/.npmignore.publishr#L2 and https://unpkg.com/radium@0.19.3/.babelrc  Should I remove that line?

/cc @HsuTing

**Comment by alexlande** [comment]
Ah, yeah, I guess so. There's no valid reason for us to have it in npm versions, right? Nothing I can think of.

**Comment by ryan-roemer** [comment]
Only valid reason is if someone wanted to use https://unpkg.com/radium@0.19.3/src/ instead of https://unpkg.com/radium@0.19.3/lib/

**Comment by alexlande** [comment]
Yeah, I'm good not considering that a valid use case 👍

**Pull request closed without merging**
