### PR TITLE
Support nested arrays in styles

### PR DESCRIPTION
**Pull request by almost**
As request in #334. I know you were talking about making this a plugin but it seems to be that there wouldn't be any downside to supporting it by default. What do you think?

### CODE REVIEW

**Comment by ianobermiller** [comment]
Please add tests.

**Comment by almost** [comment]
Sure, I've just added a test. Let me know if you need anything else

**Comment by richardfickling** [comment]
thanks for making this @almost! Looks like the tests will pass CI if you remove the console.log statement

**Comment by almost** [comment]
Sorry! I really thought I'd removed that. Have taken it out now

**Pull request merged**
