### PR TITLE
Support fallback CSS values

### LINKED ISSUE #183: Support fallback values
See discussion in https://github.com/FormidableLabs/radium/issues/164#issuecomment-106547441.

Plan is to add this to the prefixer; user can specify an array of values, and each one in order will be tested and used if it works:

```as
{
  color: ['rgba(255, 255, 255, 50)', '#eee']
}
```

### PR DESCRIPTION
**Pull request by ianobermiller**
Fixes #183

### CODE REVIEW

**Comment by alexlande** [comment]
Awesome. Still think this sort of needs to be in React core for server-side support, but it's great that we have something.

**Comment by alexlande** [comment]
:+1:

**Comment by sassanh** [comment]
Does it still work for you? It doesn't work here.

**Comment by DanielSinclair** [comment]
Having issues with this — and am not able to find documentation. Has this feature been removed? Why?

**Pull request merged**
