### PR TITLE
Bug: fix prefixed inline styles

### LINKED ISSUE #951: Using Radium with NextJS creates different styles on server + client
I'm using [NextJS](http://www.github.com/zeit/next.js) for both, server-side and client rendering with Radium.

First thing I noticed was that this code...

```jsx
const buttonRowStyle = {
  display: 'flex',
  justifyContent: 'space-between',
  marginTop: '20px',
};

const firstMetaDropdownStyle = {
  flex: 1,
  marginRight: '4%',
};

class ProductPage extends Component {
  render() {
    return (
      <StyleRoot>
        <div style={[buttonRowStyle]} />
        <Dropdown style={firstMetaDropdownStyle} />
      </StyleRoot>
    );
  }
}

export default Radium(ProductPage);
```

..would lead to this warning when used with Radium:

> Warning: Prop `style` did not match.
>
> Server: "-webkit-justify-content:space-between;-ms-flex-pack:justify;-webkit-box-pack:justify;display:-webkit-box,-moz-box,-ms-flexbox,-webkit-flex,flex;justify-content:space-between;margin-top:20px"
>
> Client: "display:flex;justify-content:space-between;margin-top:20px"

Looks like:

- Radium is only run on server-side (Don't know why)
- Radium adds vendor prefixes
- NextJS doesn't like server- and client styles to be different
- Chrome doesn't like the vendor fixes by Radium:

**_Screenshot from Chrome Devtools style inspector:_**
radium

So, I tried to disable vendor prefixing by removing `Radium.Plugins.prefix`:

```jsx
  function ConfiguredRadium(component) {
    return Radium({
      plugins: [
        Radium.Plugins.mergeStyleArray,
        Radium.Plugins.checkProps,
        Radium.Plugins.resolveMediaQueries,
        Radium.Plugins.resolveInteractionStyles,
        Radium.Plugins.keyframes,
        Radium.Plugins.visited,
        Radium.Plugins.removeNestedStyles,
        // Radium.Plugins.prefix,
        Radium.Plugins.checkProps,
      ],
    })(component);
  }
```

And also changed this:

`export default Radium(ProductPage);`

to this:

`export default ConfiguredRadium(ProductPage);`

But now I get this warning:

> Warning: Prop `style` did not match.
>
> Server: "-webkit-flex:1;-ms-flex:1;flex:1;margin-right:4%"
>
> Client: "flex:1;margin-right:4%"

So, now it looks like Radium decided to not add vendor prefixes to `display: flex` and `justify-content:space-between` but now it adds vendor prefixes to `flex: 1`.

## Questions

1. Why is Radium still adding vendor prefixes to `display:flex` after disabling the plugin?
2. Why is Radium not run client-side when used with NextJS?
3. Is there some kind of best practice guide of using Radium with NextJS? I only found some instructions for React SSR but those did not apply for NextJS.

### LINKED ISSUE #958: Prefixed inline styles are not resolved
Inline styles do not generate valid CSS properties, when using the (default) prefix plugin.

```js
const React = require("react") // v16.2.0
const Radium = require("radium") // v0.19.6
const ReactDOMServer = require("react-dom/server") // v16.2.0

const Foo = () => <div style={{display: "flex"}} />
const StyledFoo = Radium()(Foo)

ReactDOMServer.renderToString(<StyledFoo />)
```

The generated style (tested in [RunKit](https://npm.runkit.com/npm)) gives invalid CSS properties : 

```html
<div style="display:-webkit-box,-moz-box,-ms-flexbox,-webkit-flex,flex" … />
```

When it should be :

```html
<div style="display:-webkit-box;display:-moz-box;display:-ms-flexbox;display:-webkit-flex;display:flex" … />
```

According [to the inline-style-prefixer documentation](https://inline-style-prefixer.js.org/docs/guides/ResolvingArrays.html), array values should be resolved, using something like css-in-js-utils's `resolveArrayValue`, instead of joining the values by `;`.

### PR DESCRIPTION
**Pull request by ryan-roemer**
- Chooses last of many ISP properties on client side.
- Flattens all ISP array values on SSR.
- Switch Karma tests to headless chrome.
- Fixes #958 
- Fixes #951

Tasks:

- [x] Add a failing client-side test.
- [x] Fix prefixes for SSR. (Worst case, we can add a flag to pass at runtime by caller to indicate "isSSR")
- [x] Fix prefixes for client side.

/cc @alexlande @exogen @stefvhuynh @sunny

### CODE REVIEW

**Comment by sunny** [comment]
We solved this problem in [kitten](https://github.com/KissKissBankBank/kitten) by [adding a custom plugin](https://github.com/KissKissBankBank/kitten/blob/master/assets/javascripts/kitten/config/configured-radium.js) that resolves array values using `css-in-js-utils`'s `resolveArrayValue` right after the `prefix` plugin.

**Comment by ryan-roemer** [comment]
Current status after lots of discussion with @exogen and @alexlande --

- If SSR, then `const finalStyle = transformValues(prefixedStyle);` creating a smashed string works.
- If client side, then use last value in any detected arrays should work.

Our ssr / client unit tests should already reflect this.

**Comment by ryan-roemer** [comment]
@alexlande -- We're ready for full review. I've got to check that Travis and Appveyor still pass as I've switch to headless chrome on travis and mucked around with our karma configs. But I'm confident that the app code is ready for review in the meantime....

**Comment by ryan-roemer** [comment]
NOTE: Need `core-js` polyfills back in for IE9 on Appveyor: https://ci.appveyor.com/project/exogen/radium/build/1.0.1576/job/sdt8tf373ahw1oej

**Comment by ryan-roemer** [comment]
Released in `radium@0.21.2`

**Pull request merged**
