### PR TITLE
ensuring that defaultProps get transferred in every browser

### LINKED ISSUE #235: Radium breaks getDefaultProps on IE
I've tested this on IE9/10 (internet is too slow to download an 11 VM right now) and created some examples on my fork that demonstrate that it is Radium that is responsible.

https://github.com/bobbyrenwick/radium/tree/test-out-ie

I can't see anything that makes it immediately obvious why this is happening

### PR DESCRIPTION
**Pull request by bobbyrenwick**
This fixes #235, and doesn't require a move away from using the subclass method in order to enhance components.

### CODE REVIEW

**Comment by ianobermiller** [comment]
Don't we need to do the same for `propTypes`, `contextTypes`, and `childContextTypes`?

**Comment by bobbyrenwick** [comment]
@ianobermiller good thinking, that's done too

**Comment by ianobermiller** [comment]
Can you just add a comment why we are doing this? Just say this is for IE <10 and link to the babel caveats page. Then this should be good to go. Thanks again!

**Comment by bobbyrenwick** [comment]
@ianobermiller done!

**Comment by ianobermiller** [comment]
Nice work, thanks @bobbyrenwick!

**Pull request merged**
