### PR TITLE
Add css keyframes animation helper

### LINKED ISSUE #52: Add a way to define keyframe css animations
It would be nice to be able to specify [keyframe animations](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes) for an element in the component itself in javascript.

Thanks for this awesome library!

### PR DESCRIPTION
**Pull request by ianobermiller**
Fixes #52. Very simple to use:

```javascript
var pulseAnimation = Radium.animation({
  '0%': {width: '10%'},
  '50%': {width: '50%'},
  '100%': {width: '10%'}
});

var styles = {
  root: {
    animation: pulseAnimation + ' 3s ease 0s infinite'
  },
};
```

### CODE REVIEW

**Comment by ianobermiller** [comment]
Does anyone else think this should be called `Radium.keyframes` instead?

**Comment by colinmegill** [comment]
Yes

**Comment by ianobermiller** [comment]
Rename done! Fixed up all my crazy commits caused by using the Sync button in GitHub for Mac.

**Comment by alexlande** [comment]
@ianobermiller: Any way we can get this in without depending on `vendor-prefix`? I'd like to mull that one over a bit more.

**Comment by ianobermiller** [comment]
We could, but it wouldn't be terribly useful, as @keyframes still requires a prefix on Chrome and Safari.

**Pull request merged**
