### PR TITLE
Add appveyor config

### LINKED ISSUE #147: Add AppVeyor Windows CI
Let's bring the Windows love!

### PR DESCRIPTION
**Pull request by ianobermiller**
Fixes #147

### CODE REVIEW

**Comment by ianobermiller** [comment]
Actually, I tried to setup AppVeyor for Radium, but since I don't have admin rights to the repo I can't, but it never warned me :/

**Comment by ryan-roemer** [comment]
@ianobermiller -- I've got a setup at https://ci.appveyor.com/project/ryan-roemer/radium 

Just realized my user is attached to that -- as long as that's not a problem, should work from here. (If that is a problem, maybe some guidance to doing an org for AppVeyor?)

Also, good opportunity to add the build badge!

**Comment by ianobermiller** [comment]
Sweet, thanks Ryan. It should be running on my pull request then, right?
http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests

**Comment by ryan-roemer** [comment]
@ianobermiller -- Everything _looks_ right to me. But I think last time I set up the integration before opening the PR with the `appveyor.yml`. Can you try pushing an empty commit and see if that kicks it?

**Comment by ryan-roemer** [comment]
@ianobermiller -- Or better yet, add the badge as a new commit!

**Comment by ianobermiller** [comment]
@ryan-roemer  Running now on the merge...I'll try a new pull request with the badge, probably tomorrow.

**Comment by ryan-roemer** [comment]
@ianobermiller -- Build failed during `npm` process. Not exactly sure why (doesn't look familiar).

Possibly not related at all, but I've had some issues not running very, very modern `npm` and here's how I figured out to install modern in a different project's config (although have to use local...): https://github.com/FormidableLabs/full-stack-testing/blob/master/appveyor.yml#L7-L13

```yml
# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node $env:nodejs_version
  # Install and use local, modern NPM
  - npm install npm@next
  - node_modules\.bin\npm install
```

**Comment by ianobermiller** [comment]
Jest uses jsdom, which only works in 0.10 :/

**Comment by ryan-roemer** [comment]
The NPM issues I've seen in that past aren't specific to `v0.10` or `v0.12` -- latest of either might help (even if we're only able to stick with `v0.10` like we've got right now)

**Pull request merged**
