### PR TITLE
Remove peerDependencies so we can use it with react 0.14.0-beta1

### PR DESCRIPTION
**Pull request by dariocravero**

### CODE REVIEW

**Comment by ianobermiller** [comment]
Following [react-router](https://github.com/rackt/react-router/blob/master/package.json), let's move it to devDependencies and change to `"react": "0.13.x",` so the examples don't break.

**Comment by dariocravero** [comment]
@ianobermiller sorry I missed your comment, `react` [is already in devDependencies](https://github.com/FormidableLabs/radium/blob/master/package.json#L60) although locked to `>=0.13.3`.

**Comment by ianobermiller** [comment]
Thanks, I missed that.

**Comment by dariocravero** [comment]
Class :) Could you do a new minor release so that we can use the npm package directly? Thanks!

**Comment by ianobermiller** [comment]
Yeah I just want to merge #250 then I'll cut a release.

**Comment by dariocravero** [comment]
Perfect, thanks! :)

**Pull request merged**
