### PR TITLE
update jss info

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by kof** [comment]
Also would be nice to have this comparison in a separate repository

**Comment by kof** [comment]
And maybe some better format because editing this md file is not fun

**Comment by ianobermiller** [comment]
Agreed on both counts! Thanks for updating. Suggestions on a better format? I'd say a repo with one file per library, with some format conducive to multi-line markup.

**Comment by kof** [comment]
not sure what to suggest if simple md will be used ... might be better to generate html  using json configs.

**Comment by ianobermiller** [comment]
Yeah that works for me.

**Pull request merged**
