### PR TITLE
Use .npmignore instead of files

### PR DESCRIPTION
**Pull request by jmcriffey**
@alexlande @ianobermiller This addresses #581. I decided to go the route of excluding everything except for the folders that were in the files array. If it is preferable to exclude specific files instead, let me know.

### CODE REVIEW

**Comment by alexlande** [comment]
Nice!

I'll verify that it's working correctly this morning and merge this thing. 🔥

**Comment by jmcriffey** [comment]
@alexlande I am actually still having an issue installing from git. It seems that npm still reads the .npmignore file just like it would for the files list.

**Comment by jmcriffey** [comment]
So this actually solves the original issue but we still can't install from git.

**Comment by ryan-roemer** [comment]
@jmcriffey -- Yeah, we may need to include `src`.

@alexlande @ianobermiller -- Is that going to be a huge deal?

**Comment by alexlande** [comment]
Including `src` isn't ideal, but I don't think it would be a huge problem. It would be nice to do that for now, and then incorporate `.npmignore` into the "dirty swap on publish" scheme once that's going.

**Comment by jmcriffey** [comment]
@alexlande 'll go ahead and include src in this npm ignore file for now.

**Comment by ryan-roemer** [comment]
@jmcriffey @alexlande -- And we probably need `.babelrc` and maybe something else?

Side note -- we already have some of the 'dirty swap' in here: https://github.com/FormidableLabs/radium/blob/master/package.json#L29-L30 which _is_ removing `babel*` deps from package.json on publish. (See https://npmcdn.com/radium@0.17.1/package.json)

**Comment by jmcriffey** [comment]
It seems like src + .babelrc allows me to install from a git repo.

**Comment by alexlande** [comment]
Verified, works great :+1:

**Pull request merged**
